# -*- coding: utf-8 -*-
"""(06)_Mi_primer_programa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J5GxposfZ0C8WqddqcoqxNxIRal60KZ1
"""



"""### todo ha ido bien

## operaciones basicas
"""

numero = 3
numero_dos = 12
print (numero + numero_dos)

numero = 15
numero_dos = 10
print (numero - numero_dos)

numero = 6
numero_dos = 34
print (numero * numero_dos)

numero = 834
numero_dos = 12
print (numero / numero_dos)

nombre = "steveen"
apellido = "restrepo"
nombre_completo = nombre + " " + apellido
print (nombre_completo.title())

print (nombre_completo.upper())
print (nombre_completo.lower())

"""# listas"""

motos = ['harley', 'ducati', 'yamaha', 'kawasaki', 'indian', 'royal enfield']
print (motos)

print (motos[0].title())
print (motos[4].upper())

motos.insert(1, 'suzuki')
print (motos)

motos.sort()
print (motos)

longitud = len(motos)
print (motos)
print (longitud)